FROM  python:3
LABEL "maintainer"="Josue Canul Ordonez"
LABEL "version"="1.0.0"
LABEL "description"="Detect shoplifting suspicious behavior using both computer vision and deep learning techniques"
LABEL "license"="No license file"

# TO DO: add requirements dependencies
